# Generated by Django 5.1 on 2024-10-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_teamapikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamapikey",
            name="clear_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
