# Generated by Django 5.1 on 2024-11-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_teamapikey_key_id_teamapikey_last_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamapikey",
            name="status",
            field=models.CharField(default="active", max_length=10),
        ),
    ]
