# Generated by Django 5.1 on 2024-10-17 22:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("obstract_feed_metadata", models.JSONField()),
                ("is_public", models.BooleanField(default=False)),
                ("polling_schedule_minute", models.IntegerField(default=0)),
            ],
        ),
    ]
