# Generated by Django 5.1 on 2024-10-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obstracts_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="profile_id",
            field=models.UUIDField(default="db1681bc-d2f9-48ff-ad85-f53209c41578"),
            preserve_default=False,
        ),
    ]
