# Generated by Django 5.1 on 2024-10-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obstracts_api", "0003_feedsubsription"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="job_metadata",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
