# Generated by Django 5.1 on 2024-10-22 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obstracts_api", "0004_feed_job_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="next_polling_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 22, 20, 9, 50, 308109, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feed",
            name="polling",
            field=models.BooleanField(default=False),
        ),
    ]
