# Generated by Django 5.1 on 2024-11-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obstracts_api", "0005_feed_next_polling_time_feed_polling"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="active_job_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
