# Generated by Django 5.1 on 2024-12-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obstracts_api", "0006_feed_active_job_id_feed_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="next_polling_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feed",
            name="profile_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
