# Generated by Django 5.1 on 2024-11-13 08:20

import uuid
from django.db import migrations, models

# Generated by Django 5.1 on 2024-10-22 22:34

import uuid
from django.db import migrations

def delete_all_users(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    # Delete all users
    CustomUser.objects.all().delete()
    print("End")

def reverse_func(apps, schema_editor):
    pass




class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_avatar"),
    ]

    operations = [
        migrations.RunPython(delete_all_users, reverse_func),
    ]
