# Generated by Django 5.1 on 2024-11-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_custom_delete_all_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
