# Generated by Django 5.1 on 2024-09-03 09:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0012_2_8"),
        ("teams", "0003_team_billing_details_last_changed_team_customer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing_details_last_changed",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Updated every time an event that might trigger billing happens.",
                    ),
                ),
                (
                    "last_synced_with_stripe",
                    models.DateTimeField(
                        blank=True,
                        help_text="Used for determining when to next sync with Stripe.",
                        null=True,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="djstripe.customer",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        help_text="The associated Stripe Subscription object, if it exists",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="djstripe.subscription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
