# Generated by Django 5.1 on 2024-09-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_subscriptionmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="billing_details_last_changed",
        ),
        migrations.RemoveField(
            model_name="team",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="team",
            name="last_synced_with_stripe",
        ),
        migrations.RemoveField(
            model_name="team",
            name="subscription",
        ),
        migrations.AddField(
            model_name="invitation",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="SubscriptionModel",
        ),
    ]
