# Generated by Django 5.1 on 2024-09-26 10:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0012_2_8"),
        ("teams", "0005_remove_team_billing_details_last_changed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="billing_details_last_changed",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Updated every time an event that might trigger billing happens.",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="last_synced_with_stripe",
            field=models.DateTimeField(
                blank=True,
                help_text="Used for determining when to next sync with Stripe.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="The associated Stripe Subscription object, if it exists",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djstripe.subscription",
            ),
        ),
    ]
