# Generated by Django 5.1 on 2024-09-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0006_team_billing_details_last_changed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
