# Generated by Django 5.1 on 2024-09-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0007_alter_team_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
