# Generated by Django 5.1 on 2024-10-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0010_teamprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
