# Generated by Django 5.1 on 2024-10-22 22:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0012_team_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
