# Generated by Django 5.1 on 2024-10-22 22:34

import uuid
from django.db import migrations

def forward_func(apps, schema_editor):
    # Access a model from the apps registry
    print("start")
    Team = apps.get_model('teams', 'Team')
    # Perform a custom operation (e.g., update existing data)
    teams = Team.objects.all().delete()
    print("End")

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('your_app_name', 'previous_migration'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0013_alter_team_id"),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
