# Generated by Django 5.1 on 2024-10-22 22:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0014_auto_20241022_2234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
