# Generated by Django 5.1 on 2024-10-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obstracts_api", "0005_feed_next_polling_time_feed_polling"),
        ("teams", "0015_alter_team_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="feeds",
            field=models.ManyToManyField(
                related_name="team",
                through="obstracts_api.FeedSubsription",
                to="obstracts_api.feed",
            ),
        ),
    ]
