# Generated by Django 5.1 on 2024-10-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0016_team_feeds"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="clear_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
