# Generated by Django 5.1 on 2024-10-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0017_team_clear_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="clear_key",
        ),
    ]
