# Generated by Django 5.1 on 2024-11-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0018_remove_team_clear_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Administrator"),
                    ("member", "Member"),
                ],
                default="member",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Administrator"),
                    ("member", "Member"),
                ],
                max_length=100,
            ),
        ),
    ]
