name: Test GHCR Access

on:
  push:
    branches:
      - debug-build

jobs:
  test-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and Push Test Image
        run: |
          echo "FROM alpine" > Dockerfile
          docker build -t ghcr.io/${{ github.repository }}/test-image:latest .
          docker push ghcr.io/${{ github.repository }}/test-image:latest
